export {
  FORNECEDOR_CATEGORIAS,
  PROFISSIONAL_CATEGORIAS,
  FORNECEDOR_CATEGORIAS_FILTRO,
  PROFISSIONAL_CATEGORIAS_FILTRO,
} from './categorias-cadastro';

import { FORNECEDOR_CATEGORIAS_FILTRO } from './categorias-cadastro';

/** @deprecated Use FORNECEDOR_CATEGORIAS_FILTRO */
export const MATERIAIS_FILTRO_OPCOES: string[] = FORNECEDOR_CATEGORIAS_FILTRO;
